header, main, footer
alina-ap/worldofbeaty pull request #1
Opened 2021-02-28 14:26 UTC by alina-ap

2021-03-03 07:24 UTC, studenttsu requested changes
Привет) Хорошая работа!

Есть моменты, которые нужно поправить - они не критичные, но учесть стоит.
Осталось немного и работа по первому спринту будет принята)

2021-03-03 07:24 UTC, studenttsu commented on index.html
> +    <link rel="stylesheet" href="/css/style.css">
`нужно поправить`

Старайся использовать относительные пути для подключения сторонних ресурсов.
Ведь твоя вёрстка может лежать по пути site.com/landing, к примеру. В таком случае случае стили будут не найдены.

Открыл твою работу из архива и стили не были найдены по адресу /css/style.css

![image](https://user-images.githubusercontent.com/12005449/109767940-d5100680-7c2a-11eb-9a26-3528efce0d3a.png)

2021-03-03 07:24 UTC, studenttsu commented on index.html
> +        <footer class="footer">
`нужно исправить`

футер стилями нужно прижать к низу, в независимости от основного контента страницы

2021-03-03 07:24 UTC, studenttsu commented on index.html
> +                    <div class="col3">
`нужно поправить`

`col-3` - сейчас опечатка

2021-03-03 07:24 UTC, studenttsu commented on index.html
> +                            <ul class="nav-list nav-list-footer">
`отлично`

круто, что переиспользуешь код

2021-03-03 07:24 UTC, studenttsu commented on css/style.css
> +/* Футер */
`отлично`

задокументированный код легче и приятней читать)

2021-03-04 09:53 UTC, alina-ap commented on index.html
> +        <footer class="footer">
прижала

2021-03-04 09:53 UTC, alina-ap commented on index.html
> +                    <div class="col3">
спасибо, исправила

2021-03-04 09:54 UTC, alina-ap commented on index.html
> +    <link rel="stylesheet" href="/css/style.css">
Не совсем поняла, почему не открылись стили, но вроде исправила

2021-03-04 09:56 UTC, alina-ap commented
Спасибо за ревью! Закоммитила изменения

2021-03-05 06:26 UTC, studenttsu approved these changes

2021-03-05 06:34 UTC, merged