Feature/header
alina-ap/worldofbeaty pull request #3
Opened 2021-03-11 14:05 UTC by alina-ap

2021-03-13 09:33 UTC, studenttsu requested changes
Вполне не плохо)

Нужно поправить важные моменты - описал в комментариях

2021-03-13 09:33 UTC, studenttsu commented on css/adaptive.css
> +     .btn--large {
`нужно поправить`

Сейчас у вас позиционирование кнопки навешано прям на `.btn--large` без указания контекста.

Представим такую ситуацию - потребовался новый блок на сайте, где дизайнер использовал большую кнопку. После внесения изменений на мобилке у вас стили для кнопки в шапке применятся и к кнопке в новом блоке.

В вашем случае правильно будет на кнопку в шапке навешать класс элемента
`.hero__btn` и уже его использовать для позиционирования

2021-03-13 09:33 UTC, studenttsu commented on css/adaptive.css
> +        position: absolute;
`нужно поправить`

Абсолютого позиционирование в этом случае неоправдано, ведь вам просто нужно сделать контент центру.

Лучше скинуть позиционирование `position: static` и задать `text-align: center;`

Всего 2 свойства и никакого мучения)

2021-03-13 09:33 UTC, studenttsu commented on index.html
> +    <link rel="stylesheet" href="../css/adaptive.css">
почему у вас путь указывает на папку из другого раздела?

Я у себя открыл и стили не применились, потому что папка css находится в текущей директории где и index.html. Мы же пишем пути относительно файла, где эти пути используются.

Должно быть `./css/...`

2021-03-13 09:38 UTC, studenttsu commented
По поводу вопроса о позиционировании - удобно задать гамбургеру `position: absolute` и некоторые свойства - всё встанет на свои места.

![image](https://user-images.githubusercontent.com/12005449/111026002-7e6cae80-841a-11eb-9209-f39d2fdc0b82.png)

2021-03-13 12:55 UTC, alina-ap commented on index.html
> +    <link rel="stylesheet" href="../css/adaptive.css">
Когда я ставлю одну точку, то не загружаются стили через Live Server

2021-03-13 13:21 UTC, alina-ap commented on css/adaptive.css
> +        position: absolute;
И правда, спасибо)

2021-03-13 13:21 UTC, alina-ap commented on css/adaptive.css
> +     .btn--large {
Да, исправила

2021-03-13 13:21 UTC, alina-ap commented
С гамбургером разобралась, спасибо!

2021-03-15 04:41 UTC, studenttsu approved these changes
Удачи в работе след. спринта)

2021-03-15 11:05 UTC, merged